### ISSUE TITLE
Tailwindcss not working

### ISSUE THREAD

**Issue by brandoncc** [kabouzeid/nvim-lspinstall#23] opened 2021-04-02 06:56 UTC
Thank you for this plugin, it seems very useful!

This is my config:

```lua
local function setup_servers()
  require'lspinstall'.setup()
  local servers = require'lspinstall'.installed_servers()
  for _, server in pairs(servers) do
    require'lspconfig'[server].setup{}
  end
end

setup_servers()

-- Automatically reload after `:LspInstall <server>` so we don't have to restart neovim
require'lspinstall'.post_install_hook = function ()
  setup_servers() -- reload installed servers
  vim.cmd("bufdo e") -- this triggers the FileType autocmd that starts the server
end
```

I use `nvim-compe`, which has this config: 

```lua
local has_compe, compe = pcall(require, 'compe')
if has_compe then
  compe.setup {
    enabled = true;
    autocomplete = true;
    debug = false;
    min_length = 1;
    preselect = 'enable';
    throttle_time = 80;
    source_timeout = 200;
    incomplete_delay = 400;
    max_abbr_width = 100;
    max_kind_width = 100;
    max_menu_width = 100;
    documentation = true;

    source = {
      path = true;
      buffer = true;
      calc = true;
      nvim_lsp = true;
      nvim_lua = true;
      ultisnips = true;
      spell = true;
      tags = true;
      nvim_treesitter = true;
    };
  }
end
```

I have installed the tailwindcss lsp server, and it seems to be functioning:

```

  Configured servers: tailwindcss 
  Neovim logs at: /Users/brandoncc/.cache/nvim/lsp.log 
   
  1 client(s) attached to this buffer: tailwindcss 
   
    Client: tailwindcss (id 1) 
    	root:      /Users/brandoncc/dev/timely 
    	filetypes: aspnetcorerazor, blade, django-html, edge, ejs, erb, gohtml, haml, handlebars, hbs, html, html-eex, jade, leaf, liquid, markdown, mdx, mustache, njk, nunjucks, php, razor, slim, twig, css, less, postcss, sass, scss, stylus, sugarss, javascript, javascriptreact, reason, rescript, typescript, typescriptreact, vue, svelte 
    	cmd:       node ./tailwindcss-intellisense/extension/dist/server/index.js --stdio 
    	 
   
   
  1 active client(s):  
   
    Client: tailwindcss (id 1) 
    	root:      /Users/brandoncc/dev/timely 
    	filetypes: aspnetcorerazor, blade, django-html, edge, ejs, erb, gohtml, haml, handlebars, hbs, html, html-eex, jade, leaf, liquid, markdown, mdx, mustache, njk, nunjucks, php, razor, slim, twig, css, less, postcss, sass, scss, stylus, sugarss, javascript, javascriptreact, reason, rescript, typescript, typescriptreact, vue, svelte 
    	cmd:       node ./tailwindcss-intellisense/extension/dist/server/index.js --stdio 
    	 
   
   
  Clients that match the filetype typescriptreact.javascript.typescript.javascriptreact.javascript-react.javascript_react: 
```

and my lsp logs:

```
[ START ] 2021-04-01T23:52:27-0700 ] LSP logging initiated
[ WARN ] 2021-04-01T23:52:42-0700 ] /usr/local/share/nvim/runtime/lua/vim/lsp/handlers.lua:108 ]	"The language server tailwindcss triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
```

I don't understand why, but I don't get any completion recommendations. Am I doing something wrong?

Thanks!

**Comment by kabouzeid** [comment] 2021-04-02 09:52
Thanks for the detailed report, it’s very helpful! Just be looking at it I don’t see anything wrong in your confit, and since it’s attached it *should* be working.

Maybe an obvious question: do you get any other nvim-compe completions, or is it just not popping up at all?

**Comment by brandoncc** [comment] 2021-04-02 14:40
Thank you for the quick response 😄 I do get other completions from buffer and ultisnips.

By the way, Just to make sure I understood how the lsp was intended to function, I installed the extension in VSCode, went to the same file, and made the same edits I was making in neovim. I was given completions by VSCode, so I think I am using it correctly.

For further debugging, here is the file I am editing:

```tsx
import * as React from 'react';
import * as ReactDOM from 'react-dom';

function AppContainer() {
  return (
    <div className="bg-white dark:bg-gray-800 px-4 py-2 h-full container">
      test
    </div>
  );
}

function render() {
  ReactDOM.render(<AppContainer />, document.querySelector('#app'));
}

render();

if (module.hot) {
    module.hot.accept();
}
```

You can see the tailwind classes there. I removed them and tried typing them again and the only completions I get for them are from the buffer.

Even more debugging... I just made sure my neovim config is updated at https://github.com/brandoncc/nvim if you would like to use my config to debug.

I am using node v14.16.0 (npm v6.14.11) and here is my neovim version output:

```
NVIM v0.5.0-dev+1160-g0f7b6b2ef
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/brandoncc/dev/neovim/build/config -I/Users/brandoncc/dev/neovim/src -I/Users/brandoncc/dev/neovim/.deps/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/usr/local/opt/gettext/include -I/Users/brandoncc/dev/neovim/build/src/nvim/auto -I/Users/brandoncc/dev/neovim/build/include
Compiled by root@Brandons-MBP.localdomain

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

And....for good measure, here is a screenshot:

![image](https://user-images.githubusercontent.com/543973/113425292-77382100-9386-11eb-945f-96451208921b.png)


I don't know what else I might be able to provide, but feel free to ask!

**Comment by kabouzeid** [comment] 2021-04-02 15:50
Hmm I don't know what going on. I even downloaded your whole config and it works for me. 

Please set `vim.lsp.set_log_level("debug")` type a bit around and post your LSP logs again. Also remember that tailwinds lang server needs about 10 secs to start until it shows as "attached" in :LspInfo

**Comment by kabouzeid** [comment] 2021-04-02 16:30
If `/Users/brandoncc/dev/timely` is not actually the root dir of your project where `tailwind.config.js` lives, then a2cf933081bf24aa1f230c491ef757cefaf4f5cd should fix your issue.

**Comment by brandoncc** [comment] 2021-04-02 16:54
Here is the output of `ls`l in `~/timely`:

```
  ~/d/timely  ls
node_modules               postcss.config.js          tailwind.config.js         webpack.main.config.js     webpack.renderer.config.js yarn-error.log
package.json               src                        tsconfig.json              webpack.plugins.js         webpack.rules.js           yarn.lock
```

I pushed my repo (it is basically a new electron-forge app with tailwind added) [here](https://github.com/brandoncc/timely) in case something in that config catches your eye (this is the first time I have ever used tailwind, so I can't even debug my own config for that unfortunately).

[Here](https://pastebin.com/07Ubxq3G) is the log output with debugging on.

Thank you for your time, I sincerely appreciate it.

**Comment by kabouzeid** [comment] 2021-04-02 17:13
Have you forgotten to `yarn install` in your timely project?

After running `yarn install` completion is working as expected.

**Comment by brandoncc** [comment] 2021-04-02 18:28
I just verified that I did that as well. Thank you for your time and attempt to fix this. I'll keep digging into it on my own, since I know it should be working.

By the way, I use fish shell, do you think that could have anything to do with it?

**Comment by kabouzeid** [comment] 2021-04-02 19:32
Hmm your shell should not affect this, but you can easily try if launching bash or zsh before launching nvim fixes that.

You can just type `bash` in fish to launch a bash shell :)

**Comment by brandoncc** [comment] 2021-04-02 22:39
Thanks. I realize that, but vim will use the default shell as well. I might try `chsh` to switch over to zsh and see if it matters. Which shell do you use?

**Comment by kabouzeid** [comment] 2021-04-02 23:16
I'm using `zsh`. I don't think it will help, but it might be worth a try.

Does completion work with other language servers?

**Comment by brandoncc** [comment] 2021-04-03 03:25
I just installed the typescript server and that is working fine:

![image](https://user-images.githubusercontent.com/543973/113466533-9029ec00-93f1-11eb-9ba2-fe28a0774c66.png)

But no completions from tailwind still:

![image](https://user-images.githubusercontent.com/543973/113466494-3cb79e00-93f1-11eb-9ab4-16e05b565561.png)

Did you notice anything in the debug logs that looked off? This is the first server I have had issues with. I am thinking I might need to take this issues over to the neovim repo instead.

Thanks again.

**Comment by kabouzeid** [comment] 2021-04-05 11:47
Closing this for now, since I'm almost certain the problem is not due to lspinstall. Let me know when you fixed this :)

**Closed by kabouzeid** 2021-04-05 11:47 UTC

**Comment by brandoncc** [comment] 2021-04-08 17:54
@kabouzeid I think I might have found the issue. I think it might be related to the file type or something.

No completions found, so no menu shown (.jsx):

![image](https://user-images.githubusercontent.com/543973/114073276-f67e9680-9857-11eb-868c-866def10523c.png)

TailwindCSS LSP working great (.html):

![image](https://user-images.githubusercontent.com/543973/114073410-18781900-9858-11eb-8c06-7930aced6d68.png)

As you can see, it works in an html file, but not a jsx file (or tsx, for the record). I tried running `:set ft=javascriptreact` and it didn't make any difference.

This is my config from `:LspInfo`:

```
  Client: tailwindcss (id 2)
  	root:      /Users/brandoncc/dev/freshtimer
  	filetypes: aspnetcorerazor, blade, django-html, edge, ejs, erb, gohtml, haml, handlebars, hbs, html, html-eex, jade, leaf, liquid, markdown, mdx, mustache, njk, nunjucks, php, razor, slim, twig, css, less, postcss, sass, scss, stylus, sugarss, javascript, javascriptreact, reason, rescript, typescript, typescriptreact, vue, svelte
  	cmd:       node ./tailwindcss-intellisense/extension/dist/server/index.js --stdio
```

Does this make anything come to mind? At this point, I'm not sure if this is something in the install config, or an issue with neovim itself. It seems configuration related, since it works in html files?

**Comment by brandoncc** [comment] 2021-04-08 18:05
It just decided to start working...I think it is an nvm issue, but I haven't pinned it down yet. Sorry for the trouble!

**Comment by brandoncc** [comment] 2021-04-08 19:22
@kabouzeid I'm sorry for the spam.

If I open a jsx/tsx file as the first file which triggers the tailwindcss server to start, that file never gets the tailwindcss as an lsp source. After the lsp has connected, I can open a different jsx/tsx file and the lsp works fine. If I switch back to the original file, it still doesn't have the lsp completions from tailwindcss.

If, however, I open an html file first, that file _does_ get the tailwindcss completions. Any jsx/tsx file I open after that also has the right completions.

---

Your last response came in as I was typing this out and it made me wonder what `:e` would do for me to resolve this.

If I open a jsx/tsx file and wait for the tailwindcss server to boot, then do execute `:e`...it causes the completions to work as expected! This isn't required in html files though.

I disabled all of my configuration except the following, and the problem went away:

```vim
call plug#begin('~/.vim/plugged')

Plug 'neovim/nvim-lspconfig'
Plug 'kabouzeid/nvim-lspinstall'
Plug 'hrsh7th/nvim-compe'

call plug#end()

set completeopt=menuone,noselect

lua << EOF
local has_compe, compe = pcall(require, 'compe')
if has_compe then
  compe.setup {
    enabled = true;
    autocomplete = true;
    debug = false;
    min_length = 1;
    preselect = 'enable';
    throttle_time = 80;
    source_timeout = 200;
    incomplete_delay = 400;
    max_abbr_width = 100;
    max_kind_width = 100;
    max_menu_width = 100;
    documentation = true;

    source = {
      path = true;
      buffer = true;
      calc = true;
      nvim_lsp = true;
      nvim_lua = true;
      ultisnips = true;
      spell = true;
      tags = true;
      nvim_treesitter = true;
    };
  }
end

local function setup_servers()
  require'lspinstall'.setup()
  local servers = require'lspinstall'.installed_servers()
  for _, server in pairs(servers) do
    require'lspconfig'[server].setup{}
  end
end

setup_servers()

-- Automatically reload after `:LspInstall <server>` so we don't have to restart neovim
require'lspinstall'.post_install_hook = function ()
  setup_servers() -- reload installed servers
  vim.cmd("bufdo e") -- this triggers the FileType autocmd that starts the server
end
EOF
```

It looks like there is something weird happening in one of my plugins or configuration. I will definitely update this thread when I figure it out. I appreciate your time on this, and apologize for the fact that it didn't end up being related to this plugin.

**Comment by brandoncc** [comment] 2021-04-08 20:00
I found it:

```
" coc wants javascriptreact and typescriptreact, the others are to support
" honza/vim-snippets snippets
autocmd BufRead,BufNewFile *.jsx setlocal filetype=javascriptreact.javascript.javascript-react.javascript_react
autocmd BufRead,BufNewFile *.tsx setlocal filetype=typescriptreact.javascript.typescript.javascriptreact.javascript-react.javascript_react
```

This does what I need, but is breaking the lsp server for some reason. I guess my new mission is to figure out how to set the filetypes a different way.

Thanks again!

**Comment by kabouzeid** [comment] 2021-04-08 21:05
You're welcome, I'm glad you figured it out! :)

I was also using ultisnips, but now I'm using https://github.com/hrsh7th/vim-vsnip + https://github.com/kitagry/vs-snippets for snippets.
vsnip is from the maker of compe, the advantage is that it supports snippets that are provided by the language server. This is very nice for go and rust for example. vs-snippets is just a collection of snippets for vsnip, extracted from VSCode and other sources.

**But if you want to stick with ultisnips:**
I'm not sure what `filetype=javascriptreact.javascript.javascript-react.javascript_react` does, it seems weird and hacky, and could cause different problems with these filetypes in the future. I would try to replace it with `javascriptreact` and see if everything still works.

**Comment by brandoncc** [comment] 2021-04-08 21:38
Thanks for the feedback. Ultisnips allows dot separated file types that you want to complete. For some reason, https://github.com/honza/vim-snippets/tree/master/snippets has javascript snippets under a lot of different file names, and therefore file types. You are right that is is a hack for vim overall, but it is actually a feature for ultisnips. It has worked great for a long time, this is the first time I have experienced an issue.

I like ultisnips (and I wrote a neovim plugin which allows me to create snippets from visual blocks), but I'll check out the other options. Thanks.

**Comment by brandoncc** [comment] 2021-04-08 21:41
It looks like vsnip has a feature which does exactly what I use that hack for:

```vim
" If you want to use snippet for multiple filetypes, you can `g:vsnip_filetypes` for it.
let g:vsnip_filetypes = {}
let g:vsnip_filetypes.javascriptreact = ['javascript']
let g:vsnip_filetypes.typescriptreact = ['typescript']
```

**Comment by brandoncc** [comment] 2021-04-08 21:46
Fixed!!!! I only thought of reading the Ultisnips docs because I read the vsnip readme. Thank you for your time, I really appreciate it!

```
" honza/vim-snippets has a lot of different filetypes for javascript snippets
autocmd BufRead,BufNewFile *.jsx UltiSnipsAddFiletypes javascriptreact.javascript.javascript-react.javascript_react
autocmd BufRead,BufNewFile *.tsx UltiSnipsAddFiletypes typescriptreact.typescript.typescript-react.typescript_react
```
