### ISSUE TITLE
Java support

### ISSUE THREAD

**Issue by GustavoPrietoP** [kabouzeid/nvim-lspinstall#18] opened 2021-03-27 20:10 UTC
do you guys plan on adding support for java? I feel like automating the process of getting java to work would be very very helpful since right now its kind of a pain to get java setup :smile:

**Comment by kabouzeid** [comment] 2021-03-27 20:48
This is why it's not included yet. It seems like the eclipse jdtls depends very much on the users configuration.

**Comment by kabouzeid** [comment] 2021-03-27 20:51
https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/jdtls.lua

**Comment by kabouzeid** [comment] 2021-03-28 20:37
Duplicate of: https://github.com/kabouzeid/nvim-lspinstall/issues/3

**Closed by kabouzeid** 2021-03-28 20:37 UTC
