### ISSUE TITLE
tailwindcss not giving autocompletion

### ISSUE THREAD

**Issue by Tinku10** [kabouzeid/nvim-lspinstall#56] opened 2021-05-10 12:25 UTC
Before writing this I looked at all the previous issues here, also I tried using the ```VSCode```'s tailwind extension in the ```cmd```. No solution is working till now.

Using ```LspInfo``` my buffer is detecting tailwindcss and it is there in active client section. But it is not giving any completion at all in any files (I tried with html, html in angular, and vue files).

Is there something I am missing? Here is my [setup](https://github.com/Tinku10/nvim/blob/main/lua/lsp/lib/tailwind/setup.lua) for tailwind lsp.

**Comment by kabouzeid** [comment] 2021-05-10 12:52
Not quite sure why it's not working, I don't see any obvious issues in your config.
One thing to keep in mind: tailwindcss lang server needs about 10 seconds before it's ready. So when you open a file, wait for at least 10 seconds and see if completions are working then.

If it doesn't work, make sure your `cmd` exists and is executable, and double check with the provided config: https://github.com/kabouzeid/nvim-lspinstall/blob/main/lua/lspinstall/servers/tailwindcss.lua

If this also doesn't work, maybe try with the lsp setup as described in the README.

**Comment by Tinku10** [comment] 2021-05-10 13:03
@kabouzeid thanks for the reply, I tried everything. As I said, tailwind is attached and active. I don't know why it is causing an issue. Every other attached server is working fine. I also tried attaching the server VSCode is using for tailwind. That is working fine there but not in Neovim.

**Comment by kabouzeid** [comment] 2021-05-10 13:32
Sorry. Wish I could help, no idea why it's not working with your config :/

Could you try with the sample config in the README?

Closing this, because I don't think the problem is `lspinstall` related.

**Closed by kabouzeid** 2021-05-10 13:32 UTC

**Comment by Tinku10** [comment] 2021-05-10 14:24
Yeah, I also think it is not related to ```LspInstall```. Anyways thanks.

**Comment by Tinku10** [comment] 2021-05-27 14:11
Sorry to comment on a closed issue. I was able to trace the cause ( I suppose ) of this issue. But I'm unable to figure out what's the problem. Have you seen any such kind of errors @kabouzeid .

I am getting this from the log file. Earlier this error was not even showing up.

```lua
[ ERROR ] 2021-05-09T09:28:46+0530 ] ...nt_nvimlwP6tZ/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]
"rpc"	"node"	"stderr"	"internal/modules/cjs/loader.js:818\n  throw err;\n  ^\n\nError: Cannot find module 
'/home/tinku/.config/nvim/~/.local/share/nvim/lspinstall/tailwindcss/tailwindcss-intellisense/extension/dist/server/index.js'\n
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)\n    at Function.Module._load 
(internal/modules/cjs/loader.js:667:27)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)\n    
at internal/main/run_main_module.js:17:47 {\n  code: 'MODULE_NOT_FOUND',\n  requireStack: []\n}\n"
```
